#! /bin/sh


  if ! (java -version 2>&1 >/dev/null | grep "1.8" > /dev/null) ; then 
    echo "Java version is not 1.8, trying to use java8 if installed"
    lib=`update-java-alternatives -l | grep "[/].*1\.8.*" --only-matching`
    if [ -z $lib ] ; then
      $lib="/usr/lib/jvm/java-1.8.0-openjdk-amd64"
    fi
    echo "Execute \`update-alternatives --config java\` and \`update-alternatives --config javac\`"
    echo "or prepend \$PATH with $lib"
    export PATH="$lib/bin:$PATH"
    export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:/jre/bin/java::")
  else
    if !(javac -version 2>&1 >/dev/null | grep "1.8" > /dev/null); then
      echo "You're java and javac versions differ"
      exit 1
    fi
  fi

cd "$(dirname "$0")"

git submodule update --init --remote --rebase

cd contrib/wala
mvn verify -DskipTests=true -e

cd ../parameter-setter
./gradlew fatJar
