/**
 * This file is part of the Joana IFC project. It is developed at the
 * Programming Paradigms Group of the Karlsruhe Institute of Technology.
 *
 * For further details on licensing please read the information at
 * http://joana.ipd.kit.edu or contact the authors.
 */
package conc.cliser.dt;

/** DaytimeIterativeUDPServer.java
 *  Auto-generated by Cliser, Mon Jun 19 10:50:33 EDT 2000,
 *   except for the body of the method:
 *     DaytimeIterativeUDPServer.interactWithClient().
 *
 *  See http://cs.calvin.edu/~cliser/ for more details.
 */

import java.util.Date;

import conc.cliser.dt.cliser.IterativeUDPServer;

class DaytimeIterativeUDPServer extends IterativeUDPServer {
    public DaytimeIterativeUDPServer(int localPort) {
        super("Daytime", localPort);
    }
    
    public String recieved;

    public void interactWithClient() {
        recieved = this.receive();
        this.send((new Date()).toString());
    }

    public static void main(String [] args) {
        DaytimeIterativeUDPServer myServer = null;

        if (args.length == 0)
            myServer = new DaytimeIterativeUDPServer(13);
        else if (args.length == 1)
            myServer = new DaytimeIterativeUDPServer( Integer.parseInt(args[0]) );
        else {
            System.err.println("\nUsage: java DaytimeIterativeUDPServer [<port>]\n");
            System.exit(1);
        }

        myServer.run();
    }
}

