/**
 * This file is part of the Joana IFC project. It is developed at the
 * Programming Paradigms Group of the Karlsruhe Institute of Technology.
 *
 * For further details on licensing please read the information at
 * http://joana.ipd.kit.edu or contact the authors.
 */
package conc.cliser.dt;

/** DaytimeUDPClient.java
 *  Auto-generated by Cliser, Mon Jun 19 10:50:30 EDT 2000,
 *   except for the body of method:
 *     DaytimeUDPClient.interactWithServer().
 *
 *  See http://cs.calvin.edu/~cliser/ for more details.
 */

import conc.cliser.dt.cliser.UDPClient;

class DaytimeUDPClient extends UDPClient {
    public DaytimeUDPClient(String remoteHost, int remotePort) {
        super("Daytime", remoteHost, remotePort);
    }

    public void interactWithServer() {
        this.send("Hi");
        System.out.println(this.receive());
    }

    public static void main(String [] args) {
        DaytimeUDPClient myClient = null;

        if (args.length == 1)
            myClient = new DaytimeUDPClient(args[0],13);
        else if (args.length == 2)
            myClient = new DaytimeUDPClient(args[0], Integer.parseInt(args[1]));
        else {
            System.err.println("\nUsage: java DaytimeUDPClient <server> [<port>]\n");
            System.exit(1);
        }

        myClient.run();
    }
}

