#! /bin/sh

cd "$(dirname "$0")"
java -jar bin/openapi-generator-cli.jar generate -g java -i schemas/petstore/petstore.yaml -o schemas/petstore/sources
java -jar bin/openapi-generator-cli.jar generate -g jaxrs-cxf -i schemas/petstore/petstore.yaml -o schemas/petstore/server
