/**
 * This file is part of the Joana IFC project. It is developed at the
 * Programming Paradigms Group of the Karlsruhe Institute of Technology.
 *
 * For further details on licensing please read the information at
 * http://joana.ipd.kit.edu or contact the authors.
 */
package conc.cliser.kk;

/** KnockKnockTCPClient.java
 *  Auto-generated by Cliser, Mon Jun 19 14:06:53 EDT 2000,
 *   except for the body of method:
 *     KnockKnockTCPClient.interactWithServer().
 *
 *  See http://cs.calvin.edu/~cliser/ for more details.
 */

import conc.cliser.kk.cliser.TCPClient;

class KnockKnockTCPClient extends TCPClient {
    public KnockKnockTCPClient(String remoteHost, int remotePort) {
        super("KnockKnock", remoteHost, remotePort);
    }

    private String received1;
    
    public void interactWithServer() {
        received1 = this.receive();

        if (received1.equalsIgnoreCase("Knock knock")) {
            System.out.println(received1);
            String sent1 = "Who's there?";
            System.out.println(sent1);
            this.send(sent1);
            String received2 = this.receive();
            System.out.println(received2);
            String sent2 = received2 + " who?";
            System.out.println(sent2);
            this.send(sent2);
            String received3 = this.receive();
            System.out.println(received3);

        } else {
            System.err.println("KnockKnockTCPClient.interactWithServer(): "
                    + "'Knock knock' expected, "
                    + received1 + "' received");
            System.exit(1);
        }
    }

    public static void main(String [] args) {
        KnockKnockTCPClient myClient = null;

        if (args.length == 1)
            myClient = new KnockKnockTCPClient(args[0],1234);
        else if (args.length == 2)
            myClient = new KnockKnockTCPClient( args[0], Integer.parseInt(args[1]) );
        else {
            System.err.println("\nUsage: java KnockKnockTCPClient <server> [<port>]\n");
            System.exit(1);
        }

        myClient.run();
    }
}

