//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.02.26 at 10:58:55 AM CET
//


package edu.kit.joana.ui.ifc.wala.rifl.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "parameter")
public class Parameter {

	@XmlAttribute(name = "methodname", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String methodname;
	@XmlAttribute(name = "position", required = true)
	@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	protected String position;

	/**
	 * Gets the value of the methodname property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 * 
	 */
	public String getMethodname() {
		return methodname;
	}

	/**
	 * Sets the value of the methodname property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 * 
	 */
	public void setMethodname(final String value) {
		this.methodname = value;
	}

	/**
	 * Gets the value of the position property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 * 
	 */
	public String getPosition() {
		return position;
	}

	/**
	 * Sets the value of the position property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 * 
	 */
	public void setPosition(final String value) {
		this.position = value;
	}

}
