//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.02.26 at 10:58:55 AM CET
//


package edu.kit.joana.ui.ifc.wala.rifl.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"sources",
		"sinks"
})
@XmlRootElement(name = "sourcesandsinks")
public class Sourcesandsinks {

	@XmlElement(required = true)
	protected Sources sources;
	@XmlElement(required = true)
	protected Sinks sinks;

	/**
	 * Gets the value of the sources property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link Sources }
	 * 
	 */
	public Sources getSources() {
		return sources;
	}

	/**
	 * Sets the value of the sources property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link Sources }
	 * 
	 */
	public void setSources(final Sources value) {
		this.sources = value;
	}

	/**
	 * Gets the value of the sinks property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link Sinks }
	 * 
	 */
	public Sinks getSinks() {
		return sinks;
	}

	/**
	 * Sets the value of the sinks property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link Sinks }
	 * 
	 */
	public void setSinks(final Sinks value) {
		this.sinks = value;
	}

}
