#! /bin/bash

set -e

cd "$(dirname "$0")"

echo "build packages"
./package

echo "start servers"

jobs=()
trap 'kill $jobs' EXIT HUP TERM INT
(cd shop; mvn exec:java) & jobs+=($!)
(cd wiki; mvn exec:java) & jobs+=($!)


sleep 100000
